### ISSUE TITLE
Extending Date picker with time (hour/minute) option

### ISSUE THREAD

**Issue by kthuno** [sweco/sweco-digital-platforms#15]
As stated in the title, would be a very usable feature to have the date-picker component be extending with an option for also choosing a time (hour and minute) so it collectively can produce a timestamp on the form DD/MM-YYYY TT:MM

Best regards,
Kasper Thunø
GIS&IT, Sweco DK

**Comment by sweco-sepros** [comment]
I think you will find your specific config for the datetimepicker docs:
http://eonasdan.github.io/bootstrap-datetimepicker/#enableddisabled-dates

**Comment by t800t8** [comment]
Hi @sweco-sepros,

I cloned your repository and try to set up datetimepicker with default configuration (it should show time chooser) but it broke the date chooser. You can see the screen shot here https://ibb.co/472H97C

Here is my code

```
    $('.datetimepicker').datetimepicker({
        icons: {
          time: 'fa fa-clock-o',
          date: 'fa fa-calendar',
          up: 'fa fa-angle-up fa-lg',
          down: 'fa fa-angle-down fa-lg',
          previous: 'fa fa-angle-left fa-lg',
          next: 'fa fa-angle-right fa-lg',
          today: 'fa fa-calendar-o',
          clear: 'fa fa-times-circle',
          close: 'fa fa-times-circle'
        }
      });
```

BTW seems the datetimepicker you use only works properly with Bootstrap 3. Please consider to replace it with this one https://tempusdominus.github.io/bootstrap-4/

**Comment by sweco-sepros** [comment]
See:
https://github.com/sweco/sweco-digital-platforms/issues

Next version is planned yet. Maybe i will get an order to do it in may.

**Comment by t800t8** [comment]
Hi @sweco-sepros,

Thanks for quick response.
