### ISSUE TITLE
How can I take full width of the page into use

### ISSUE THREAD

**Issue by Sweco-fivanl** [sweco/sweco-digital-platforms#16]
I have dashboards that contain huge amount of gadgets. The sweco styling forces everything into a fixed width band at the center of the browser. How can I avoid this?
![image](https://user-images.githubusercontent.com/34161845/49876117-4fc29080-fe2b-11e8-874c-3f2aeba4026f.png)

**Comment by sweco-sepros** [comment]
Just follow Bootstrap markup for containers
https://getbootstrap.com/docs/4.3/layout/overview/#containers
