### ISSUE TITLE
Datetimepicker dependency change

### ISSUE THREAD

**Issue by sweco-sepros** [sweco/sweco-digital-platforms#18]
Change from the outdated 
https://github.com/Eonasdan/bootstrap-datetimepicker
to the latest version of
https://github.com/tempusdominus/bootstrap-4

**Comment by t800t8** [comment]
Hi @sweco-sepros,

I tried to replace Eonasdan DateTimePicker with the Tempusdominus one for Bootstrap 4 but still have problem with default configuration

`$('.datetimepicker').datetimepicker({
        icons: {
          time: 'fa fa-clock-o',
          date: 'fa fa-calendar',
          up: 'fa fa-angle-up fa-lg',
          down: 'fa fa-angle-down fa-lg',
          previous: 'fa fa-angle-left fa-lg',
          next: 'fa fa-angle-right fa-lg',
          today: 'fa fa-calendar-o',
          clear: 'fa fa-times-circle',
          close: 'fa fa-times-circle'
        }
      });`

The date picker doesn't display at initial. There is only date/time switcher there. And after switch to time picker, it still appears even I clicked the switcher (still no date picker displays).

Please help to check this case when you finish the issue. Thank you.

**Comment by sweco-sepros** [comment]
v.4.2.0
