### ISSUE TITLE
Typeahead (sökfunktions input)

### ISSUE THREAD

**Issue by NinaMayor** [sweco/sweco-digital-platforms#3]
Twitter Typeahead for Bootstrap. Skulle vi kunna inkludera den i huvudprojektet? Tack.

**Comment by sweco-sepros** [comment]
I think it´s a good idea to just include the styling but not scripts for https://twitter.github.io/typeahead.js/ and also http://autocomplete-js.com/

**Comment by sweco-sepros** [comment]
Solved in version 1.1.1
